# Generated by Django 3.2.5 on 2021-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Initilize'), (1, 'In progress'), (2, 'Client Approval'), (3, 'Close'), (4, 'Re-Open')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
