# Generated by Django 4.2.11 on 2024-04-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('course', models.IntegerField(choices=[(0, 'Basics to Programming and project management tools'), (1, 'Advance Python / Django'), (2, 'Full Stack API & React JS'), (3, 'Mobile Development with Flutter'), (4, 'Artificial Intelligence and Machine Learning'), (5, 'AWS Cloud Engineering')], default=0)),
                ('address', models.TextField(max_length=600)),
                ('reference_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
